name: CI/CD AWS TEST

on:
  push:
    branches: [ master ]

jobs:
  build: 
    runs-on: ubuntu-latest
 
    steps: 
    - uses: actions/checkout@v2
    
    - name: Build container_compose
      run: docker-compose up -d --build
    
deploy: 
  need: build 
  runs-on: ubuntu-latest

  steps: 
    - uses: actions/checkout@v2
    - name: Deploy in EC2 
      env: 
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOSTNAME : ${{ secrets.HOSTNAME  }}
          USER_NAME : ${{ secrets.USER_NAME  }}
      
      run: |
        cd /home/ubuntu/TestAwsGitHubActions/
        git pull 
        docker-compose up -d --build