name: CI/CD AWS TEST

on:
  push:
    branches: [ main ]

jobs:   
  deploy: 
    runs-on: ubuntu-latest

    steps: 
      - name: Deploy in EC2 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME  }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY  }}
          script: |
            touch a
            cd /home/ubuntu/TestAwsGitHubActions/
            git pull 
            docker-compose -f ~/TestAwsGitHubActions/docker-compose.yml up -d --build