name: CI/CD AWS TEST

on:
  push:
    branches: [main]

env:
  HOST: ${{ secrets.HOSTNAME }}
  USER: ${{ secrets.USER_NAME }}
  KEY: ${{ secrets.AWS_PRIVATE_KEY  }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker Image
        run: docker build . --file Dockerfile --tag web:$(date +%s)
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: chechout
        uses: actions/checkout@v3
      - name: Create key.pem
        run: echo "$KEY" | tr -d '\r' > key.pem && chmod 600 key.pem
      - name: Check key.pem
        run: cat key.pem         
      - name: Deploy in EC2
        run:  | 
            ssh -o StrictHostKeyChecking=no -i key.pem ${USER}@${HOST} '
                cd /home/ubuntu/TestAwsGitHubActions &&
                docker-compose up --build
            '
