name: CI/CD AWS TEST

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker Image
        run: docker build . --file Dockerfile --tag web:$(date +%s)
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create key.pem
        env:
          HOST: ${{ secrets.HOSTNAME }}
          USER: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
        run: |
          echo ${KEY} > key.pem
    steps:
      - uses: actions/checkout@v3
      - name: Deploy in EC2
        env:
          HOST: ${{ secrets.HOSTNAME }}
          USER: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
        run: |
          echo ${KEY} > key.pem
          ssh -i key.pem ${USER}@${HOST} touch llegue