name: CI/CD AWS TEST

on:
  push:
    branches: [main]

env:
  HOST: ${{ secrets.HOSTNAME }}
  USER: ${{ secrets.USERNAME }}
  KEY: ${{ secrets.AWS_PRIVATE_KEY  }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker Image
        run: docker build . --file Dockerfile --tag web:$(date +%s)
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create key.pem
        uses: actions/checkout@v3
        run: |
          echo ${KEY} > key.pem

      - name: Deploy in EC2
      - uses: actions/checkout@v3
        run: |
          echo ${KEY} > key.pem
          ssh -i key.pem ${USER}@${HOST} touch llegue
